# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags:
    - '*'
jobs:
    test-curl-action:
        name: 'Perform REST API'
        runs-on: ubuntu-latest
        steps:
            - name: 'Call API'
              #uses: indiesdev/curl@v1
              id: api
#               with:
#                 url: https://api.github.com/repos/rizwanejaznisum/test-repo2/releases
#                 method: 'GET'
#                 headers: '{"Authorization": "Basic cml6d2FuZWphem5pc3VtOm5pc3VtMTIz"}'
              run: |
                  curl --fail --request GET --header "Authorization: Basic cml6d2FuZWphem5pc3VtOm5pc3VtMTIz" --url "https://api.github.com/repos/rizwanejaznisum/test-repo2/releases"
            - name: 'Use response'
              run: echo ${{ steps.api.outputs.response }}
